defaultFilters: &defaultFilters
  filters:
    branches:
      only:
        - master
        - release-2.5
        - release-2.6
        - release-2.7
workflows:
  version: 2
  main:
    jobs:
      - node9:
          <<: *defaultFilters
      - node8:
          <<: *defaultFilters
      - node6:
          <<: *defaultFilters
  nightly:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only: master
    jobs:
      - node9:
          <<: *defaultFilters
          context: nightlies
      - node8:
          <<: *defaultFilters
          context: nightlies
      - node6:
          <<: *defaultFilters
          context: nightlies

base: &base
  environment:
    - workerCount: 4
    - timeout: 400000
  steps:
    - checkout:
        post:
          - git submodule update --init --recursive
    - run: |
        npm uninstall typescript --no-save
        npm uninstall tslint --no-save
        npm install
        #npm update Appeared in Jenkins only
        npm test

version: 2
jobs:
  node9:
    docker:
      - image: circleci/node:9
    <<: *base
  node8:
    docker:
      - image: circleci/node:8
    <<: *base
  node6:
    docker:
      - image: circleci/node:6
    <<: *base
